
version: '3'
services:
  postgres-go:
    image: postgres:latest
    container_name: postgres-go
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME} 
    ports:
      - '5455:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - go-net
      
  app:
    container_name: books_go
    build: .
    ports: 
      - 5000:${APP_PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres-go          
    networks:
      - go-net
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_go
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-go
    ports:
      - "5051:80"
    networks:
      - go-net
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

networks:
  go-net:
    driver: bridge